- 👨‍💻 Hello explorers I am @thefinest1, I haven't been really invested into my git responsibilities, and this is my response
- 🐔 I am not interested in simple stuff you see everyday, I want to put a gui kali desktop on a SM-G phone using termux and vncviewer.(bro how are you gonna have a multi-platform repo with just a phone)  
- 🕵 I’m currently learning 'How TO BE A BOSS' but for real thefinest1 is not just a name sake it is predestined to be a distrubtor of thefinest <Technological Coding, Developers of Software, and Electronic Powerhouse w/ reliable and up to date scripts and codes. 
- 💯 I’m looking to collaborate on anything that seems like a cheat of everyday life. PC's network/wifi is down, but you in the middle of a important mission only attainable on Mint Linux what do you do ? what I would do is take the hardest route and make it reality. I could use my phones Hotspot but no, I'm going to turn my Hotspot on just to updatebone of my network drivers to to use a samsung technologies Ltd. ipv4 ipv6 Wifi modem connector adapter, download 'samsung usb drivers' turn on my mobile Hotspot and USB tethering, got to developer options and change usb setting to usb tethering, go to my phone dialer app and type *#*#0808# and configure those usb settings, and I'm guess you figure out the rest if you can't then you should really check out this repo 
- 💬+🤳+👀+🧑‍💻= How to reach me : <[,thefinest2500@gmail.com | be real with you I'm not very socialable unless the right variables like a good day and that's anyday I'm the thefinest1(LOl) guess what that's every F** day but sadly not every hour. ~phone # 1800-thefinest/I'mabossafterwork, that's not a real phone # wanna see how many people read this shows what kinda effort you got phone number[336-314-5455] I don't check my voice mails like that send a text with "GitHub username,1 idea or info that drew your attention to me, and a simple summary of what you need.
- 🫅🎅🦸‍♂️ Pronouns: "A BOSS","thefinest","Santa" cause I bear gifts "hero" cause I gave a reason to give your kids or spouse, why you are busy.(he,him,yo bro)
- 🧠✏fact: I have a PC 'HP Notebook with a mmc drive 64gb that had S mode w/ windows on it. it was annoying so I took it off, then I think for some reason goofing around I updated my hard drive driver to a optical drive when it don't have on, so I've usb booted Linux mint but it doesn't save so I'm going to put same or similar desktop on my phones until I find fix, but I never done this before but I have experience with developing coding and terminal/termux 

<!---
thefinest1one/multi-platform_gui-dsktp-envir-vnc-TerminalBased.termux.repo.com is a ✨ special ✨ repository because its `READ.ME` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
